routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
 			
 			Route::get('dashboard',  ['as' => 'dashboard',  'uses' => 'DashboardController@index']);
 			Route::get('profile',  ['as' => 'profile',  'uses' => 'UserController@profile']);
 			Route::post('profile',  ['as' => 'profile.update',  'uses' => 'UserController@profileUpdate']);
 			//Route::resource('user', 'UserController');
 			Route::resource('roomtypes', 'RoomTypeController');
 			Route::resource('hotel', 'HotelController');
 			Route::resource('reservation', 'ReservationController');
 			Route::resource('inquiry', 'InquiryController');
 			Route::get('reservation/publish/{id}', 'ReservationController@publish')->name('reservation.publish');
 			Route::get('reservation/genderone/{id}', 'ReservationController@genderone')->name('reservation.genderone');

 			Route::resource('addstaff', 'AddStaffController');
 			Route::resource('room', 'RoomController');


			Route::resource('service', 'ServicesController');
 			Route::resource('slider', 'SliderController');
 			Route::get('slider/publish/{id}', 'SliderController@publish')->name('slider.publish');
 			
 			Route::resource('amenity', 'AmenityController');

 			Route::get('roomtypes/{id}/delete', ['as' => 'roomtypes.delete', 'uses' => 'RoomTypeController@destroy']);


 			Route::get('room/{id}/delete', ['as' => 'room.delete', 'uses' => 'RoomController@destroy']);




});

Auth::routes();

/*FrontEnd*/
Route::get('/', 'Web\HomeController@index')->name('home');
Route::get('/about-us', 'Web\HomeController@aboutUs')->name('about-us');
Route::get('/services', 'Web\HomeController@services')->name('services');
Route::get('/rooms', 'Web\RoomsController@index')->name('rooms');
Route::get('reservation/{id}', 'Web\RoomsController@booking')->name('reservation.booking');
Route::get('reservation/publish/', 'Web\RoomsController@publish')->name('reservation.publish');
Route::get('/rooms/{id}', 'Web\RoomsController@getSingleRoom')->name('rooms.title');
Route::get('/contact', 'Web\HomeController@contact')->name('contact');
Route::post('/submitContactForm', 'Web\HomeController@submitContactForm')->name('submitContactForm');

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Html;

class Room extends Model
{
    protected $table = 'rooms';

    protected $fillable = ['room_code','description','sell_price','regular_price','room_type_id','featured_photo','no_bed','excerpt','amentity_id'];


    public function room_types()
    {
        return $this->belongsTo('App\Models\RoomType','room_type_id','id');
    }
    public function reservations()
    {
        return $this->hasMany('App\Models\Reservation','room_id','id');
    }
    public function amenities()
    {
        return $this->hasMany('App\Models\Amenity','id','amentity_id');
    }
    public function pathToImage($path) {
        if(filter_var($path,FILTER_VALIDATE_URL)){
            $path_ = $path;
        }
        else{
            $path_ = $path?url('/').'/'.$path:"";
        }
        return $path_;
    }
    public function renderImage(array $option =null) {
        return Html::image($this->pathToImage($this->image),$this->name,$option);
    }

    public function scopeHomeRooms($query){
        return $query->orderBy('created_at')->take(6)->get();
    }

    public function getExcerptAttribute($value){
        return substr($value,0,100).' ....';
    }
    


}

app/Models/RoomType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RoomType extends Model
{
    protected $table = 'room_types';
    protected $fillable = ['title','slug','description']; 
    protected $guarded = ['id','created_at','updated_at'];

    public function room(){
   	return $this->hasMany('App\Models\Room','room_id','id');
    }
    public function getTitleAttribute($value){
        return ucwords($value);
    }

}

app/Http/Controllers/Admin/RoomController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\RoomType;
use App\Models\Room;
use App\Http\Requests\Admin\Room\AddRoomRequest;
use App\Http\Requests\Admin\Room\EditRoomRequest;


class RoomController extends BaseController
{
    protected $room_types;


    public function __construct()
    {
        $this->room_types = ['' => 'Select Option'] + RoomType::pluck('title', 'id')->toArray();
        $this->model = new Room();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $rooms = Room::all();
        // dd($rooms);
            return view(parent::loadCommonDataToView('admin.room.index'), [
            'rooms' => $rooms,
        ]);
         }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view(parent::loadCommonDataToView('admin.room.create'),[
            'room_types' => $this->room_types,

        ]);
      }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,[
            'room_code'=>'required|unique:rooms',
            'excerpt'=>'required|max:250',
            'description'=>'max:600',
            'sell_price'=>'numeric',
            'regular_price'=>'required|numeric',
            'room_type_id'=>'required|exists:room_types,id',
            'image'=>'required|mimes:jpeg,bmp,png',
            'no_bed'=>'required|numeric',

        ]);

        $room = new Room();


        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $ext = $image->getClientOriginalExtension();
            $destination = 'images/room';
            $photo_name = md5(time());
            $photo_original_name = $destination . '/' . $photo_name . '.' . $ext;
            $image->move($destination, $photo_original_name);
            $room->image = $photo_original_name;
        }
        $room->room_code = $request->input('room_code');
        $room->description = $request->input('description');
        $room->sell_price = $request->input('sell_price');
        $room->regular_price = $request->input('regular_price');
        $room->room_type_id = $request->input('room_type_id');
        $room->no_bed = $request->input('no_bed');
        $room->excerpt = $request->input('excerpt');
        $room->save();

        return  redirect()->back()->with('success_message', 'New Room has been added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {

        $rooms = Room::find($id);
       return view(parent::loadCommonDataToView('admin.room.edit'),[
            'room_types' => $this->room_types,
             'rooms' => $rooms
   ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request,[
            'room_code'=>'required',
            'excerpt'=>'required|max:250',
            'description'=>'max:600',
            'sell_price'=>'required_without:regular_price|numeric',
            'regular_price'=>'required_without:sell_price|numeric',
            'room_type_id'=>'required',
            //'category_id' => 'required|exists:categories,id'
            'image' => 'nullable|image|max:3000',
            'no_bed'=>'required|numeric',

        ]);
        //dd($request->all());
        $rooms = Room::find($id);

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $destination = 'images/room';
            $extension = $image->getClientOriginalExtension();
            $image_name = $destination . '/' . md5(time()) . '.' . $extension;

            if ($rooms->image && app('files')->exists($rooms->image)) {
                app('files')->delete($rooms->image);
            }

            $image->move($destination, $image_name);
            $rooms->image = $image_name;
        }
        $rooms->room_code = $request->input('room_code');
        $rooms->description = $request->input('description');
        $rooms->sell_price = $request->input('sell_price');
        $rooms->regular_price = $request->input('regular_price');
        $rooms->room_type_id = $request->input('room_type_id');
        $rooms->no_bed = $request->input('no_bed');
        $rooms->excerpt = $request->input('excerpt');
        $rooms->includes = $request->input('includes');
        $rooms->status = $request->input('status');
        $rooms->save();

        return  redirect()->back()->with('success_message', 'New Room has been Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $row = $this->model->find($id);
        $row->delete();

        return redirect()->route('admin.room.index')->with('error_message','Room Deleted successfully!!');
    }
}

app/Http/Controllers/Web/RoomsController.php
<?php

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Slider;
use App\Models\Service;
use App\Models\Room;
use App\Models\RoomType;
use App\Models\Inquiry;
use Illuminate\Support\Facades\Validator;


class RoomsController extends Controller
{
	public function index(){
        $data['rooms'] = Room::all();
        return view('frontend.rooms.index',compact('data'));
	}

    public function getSingleRoom($id)
    {
        $rooms = Room::find($id);
        return view('frontend.rooms.roomdetails',[
            'room' => $rooms
          ]);
    }
    public function booking(Request $request, $id){
        $rooms = Room::find($id);
        $arrival_date = $request->input('arrival_date');
        $departure_date = $request->input('departure_date');
        $num_adults = $request->input('num_adults');
        $num_kids = $request->input('num_kids');
        $room_type = $request->input('room_type');
        return view('frontend.rooms.reservation',[
            'room' => $rooms,
            'arrival_date' => $arrival_date,
            'departure_date' => $departure_date,
            'num_adults' => $num_adults,
            'num_kids' => $num_kids,
            'room_type' => $room_type


        ]);
    }


    public function publish($id)
    {
        $reservations = Reservation::find($id);
        $reservations->status = $reservations->status ? 0 : 1;
        $reservations->save();
        return redirect()->back();
    }


}

resources/views/admin/room/create.blade.php
@extends('admin.includes.layout')
@section ('content')
<div class="page-content-wrapper">
  <div class="page-content">
    <div class="page-bar">
      <div class="page-title-breadcrumb">
        <div class=" pull-left">
          <div class="page-title">Dashboard</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
          @include('admin.includes.breadcrumb_dashboard_link')
          <li class="active">Dashboard</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8">
        <div class="card card-box">
          <div class="card-head">
          <header>Add Rooms</header>
        </div>
        <div class="card-body " id="bar-parent">
          {!! Form::open([
            'url' => route('admin.room.store'),
            'files'=>true,
            ])
          !!}          
          @include('admin.room.inc.form')
          {{ Form::close() }}
        </div>
      </div>
    </div>
    <div class="col-lg-4">
         @include('admin.includes.flash_messages')
    </div>
  </div>
</div>
@endsection

resources/views/admin/room/edit.blade.php
@extends('admin.includes.layout')
@section ('content')
<div class="page-content-wrapper">
  <div class="page-content">
    <div class="page-bar">
      <div class="page-title-breadcrumb">
        <div class=" pull-left">
          <div class="page-title">Dashboard</div>
        </div>
        <ol class="breadcrumb page-breadcrumb pull-right">
        @include('admin.includes.breadcrumb_dashboard_link')
          <li class="active">Dashboard</li>
        </ol>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        @include('admin.includes.flash_messages')
        <div class="card card-box">
          <div class="card-head">
          <header>Edit Rooms</header>
          <button id = "panel-button"
          class = "mdl-button mdl-js-button mdl-button--icon pull-right"
          data-upgraded = ",MaterialButton">
          <i class = "material-icons">more_vert</i>
          </button>
          <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
            data-mdl-for = "panel-button">
            <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
            <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
            <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
          </ul>
          </div>
        <div class="card-body " id="bar-parent">
          
          {!! Form::open(array(
          'url' => route('admin.room.update', $rooms->id),
          'files' => true,
          'role' =>'form',
          'method'=> 'PUT',
          ))
          !!}
          
          @include('admin.room.inc.form')
          {{ Form::close() }}
        </div>
      </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/room/index.blade.php
@extends('admin.includes.layout')
@section ('content')
    <div class="page-content-wrapper">
        <div class="page-content">
            <div class="page-bar">
                <div class="page-title-breadcrumb">
                    <div class=" pull-left">
                        <div class="page-title">Room Informations</div>
                    </div>
                    <ol class="breadcrumb page-breadcrumb pull-right">
                       @include('admin.includes.breadcrumb_dashboard_link')
                        <li class="active">Dashboard</li>
                    </ol>
                </div>
            </div>
           <div class="row">
           	<div class="col-sm-12">

              @include('admin.includes.flash_messages')

           		 <div class="card card-box">
                                <div class="card-head">
                                    <header>Add Rooms</header>
                                     <button id = "panel-button" 
                                   class = "mdl-button mdl-js-button mdl-button--icon pull-right" 
                                   data-upgraded = ",MaterialButton">
                                   <i class = "material-icons">more_vert</i>
                                </button>
                                <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                                   data-mdl-for = "panel-button">
                                   <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
                                   <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
                                   <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
                                </ul>
                                </div>
                                <div class="card-body " id="bar-parent">
                                    <div class="table-scrollable">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>SN</th>
                                                <th>Room Code</th>
                                                <th>Room Type</th>
                                                <th>Short Description</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($rooms as $room)
                                                <tr>
                                                    <td>{{ $room->id }}</td>
                                                    <td>{{ $room->room_code }}</td>
                                                    <td>{{ $room->room_types->title }}</td>

                                                    <td>{{ $room->excerpt }}</td>
                                                    <td>
                                                        <a href="{{ route('admin.room.edit', $room->id) }}" class="btn btn-tbl-edit btn-xs">
                                                            <i class="fa fa-pencil"></i>
                                                        </a>

                                                        <a href="javascript:void(0);"
                                                           class="btn btn-tbl-delete btn-xs bootbox-confirm btn-delete">
                                                            <i class="fa fa-trash-o"></i>
                                                        </a> 

                                                         {!! Form::open(['id'=>'destroy-form','route' => ['admin.room.destroy', $room->id],'method'=>'DELETE']) !!}
                                                        {!! Form::close() !!}
                                                        {{-- <a href="#"  onclick="document.querySelector('#destroy-form').submit();return false;"
                                                           class="btn btn-tbl-delete btn-xs bootbox-confirm">
                                                            <i class="fa fa-trash-o"></i>
                                                        </a> --}}
                                                        {{--<a href="{{ route('admin.room.delete',$room->id) }}" class="btn btn-tbl-edit btn-xs" id="btn-delete">
                                                            <i class="fasss fa-trash-o"></i>
                                                        </a>--}}
                                                        {{--        {!! Form::open(['id'=>'destroy-form','route' => ['admin.roomtypes.destroy', $types->id],'method'=>'DELETE']) !!}
                                                               {!! Form::close() !!} --}}
                                                        <script type="text/javascript">
                                                        $(function(){
                                                            $(".btn-delete").on('click', function (event) {
                                                                event.preventDefault();
                                                            var $this = $(this);

                                                            swal({
                                                                title: "Are you sure?",
                                                                text: "Once deleted, you will not be able to recover this data!",
                                                                icon: "warning",
                                                                buttons: true,
                                                                dangerMode: true,
                                                            },
                                                            function (isConfirm) {
                                                            if (isConfirm) {
                                          
                                            
                                                                
                                                                location.href = $this.attr('href');
                                                                document.getElementById('destroy-form').submit();
                                                                swal("Poof! Your data has been deleted!", {
                                                                icon: "success",
                                                            });
                                                        } else {
                                                            swal("Your data is safe!");
                                                        }
                                                        });
                                                    });
                                                    });
                                                        </script>

                                                    </td>

                                                </tr>
                                            @endforeach

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
           	</div>
           </div>
            
        </div>
    </div>



@endsection

@section('extra_styles')
<link rel="stylesheet" href="{{ asset('assets/admin/plugins/sweet-alert/sweetalert.min.css') }}">
@endsection

@section('extra_scripts')
<script src="{{ asset('assets/admin/plugins/sweet-alert/sweetalert.min.js') }}" ></script>

</script>

  @endsection