routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
 			
 			Route::get('dashboard',  ['as' => 'dashboard',  'uses' => 'DashboardController@index']);
 			Route::get('profile',  ['as' => 'profile',  'uses' => 'UserController@profile']);
 			Route::post('profile',  ['as' => 'profile.update',  'uses' => 'UserController@profileUpdate']);
 			//Route::resource('user', 'UserController');
 			Route::resource('roomtypes', 'RoomTypeController');
 			Route::resource('hotel', 'HotelController');
 			Route::resource('reservation', 'ReservationController');
 			Route::resource('inquiry', 'InquiryController');
 			Route::get('reservation/publish/{id}', 'ReservationController@publish')->name('reservation.publish');
 			Route::get('reservation/genderone/{id}', 'ReservationController@genderone')->name('reservation.genderone');

 			Route::resource('addstaff', 'AddStaffController');
 			Route::resource('room', 'RoomController');


			Route::resource('service', 'ServicesController');
 			Route::resource('slider', 'SliderController');
 			Route::get('slider/publish/{id}', 'SliderController@publish')->name('slider.publish');
 			
 			Route::resource('amenity', 'AmenityController');

 			Route::get('roomtypes/{id}/delete', ['as' => 'roomtypes.delete', 'uses' => 'RoomTypeController@destroy']);


 			Route::get('room/{id}/delete', ['as' => 'room.delete', 'uses' => 'RoomController@destroy']);




});

Auth::routes();

/*FrontEnd*/
Route::get('/', 'Web\HomeController@index')->name('home');
Route::get('/about-us', 'Web\HomeController@aboutUs')->name('about-us');
Route::get('/services', 'Web\HomeController@services')->name('services');
Route::get('/rooms', 'Web\RoomsController@index')->name('rooms');
Route::get('reservation/{id}', 'Web\RoomsController@booking')->name('reservation.booking');
Route::get('reservation/publish/', 'Web\RoomsController@publish')->name('reservation.publish');
Route::get('/rooms/{id}', 'Web\RoomsController@getSingleRoom')->name('rooms.title');
Route::get('/contact', 'Web\HomeController@contact')->name('contact');
Route::post('/submitContactForm', 'Web\HomeController@submitContactForm')->name('submitContactForm');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Html;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','first_name','middle_name','last_name','contact','address',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function pathToImage($path) {
        if(filter_var($path,FILTER_VALIDATE_URL)){
            $path_ = $path;
        }
        else{
            $path_ = $path?url('/').'/'.$path:"";
        }
        return $path_;
    }
    public function renderImage(array $option=null) {
        return Html::image($this->pathToImage($this->image),$this->name,$option);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\User;



class UserController extends BaseController
{

    public function profile()
    {
        $data = [];
        $data['user'] = auth()->user();
        return view(parent::loadCommonDataToView('admin.user.profile'), compact('data'));
    }


    public function profileUpdate(Request $request)
    {
        //dd($request->all());
        $this->validateLogin($request);
        // dd($request->all());
        $user = auth()->user();

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->first_name = $request->get('first_name');
        $user->middle_name = $request->get('middle_name');
        $user->last_name = $request->get('last_name');
        $user->contact = $request->get('contact');
        $user->address = $request->get('address');
        if($request->get('password')){
            $user->password = bcrypt($request->get('password'));
        }
       
        $user->save();


        return redirect()->route('admin.profile')->with('success_message','You successfully Updated your profile.');
    }

    protected function validateLogin(Request $request)
    {

        $rules =  [
            'name' => 'required|string|unique:users,name,'.auth()->user()->id,
            'email' => 'required|string|unique:users,email,'.auth()->user()->id,
        ];

        if($request->get('password')){

            $rules['password'] = 'confirmed|string|min:6';

        }

        $this->validate($request,$rules);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

    }
}

resources/views/admin/user/profile.blade.php
@extends('admin.includes.layout')

@section('title')

User::Profile
@endsection

@section('content')

{!! Form::open([
            'url' => route('admin.profile.update'),
            'files'=>true,
            'method' =>'POST',
            ])
!!}
	<div class="page-content-wrapper">

                <div class="page-content">
                    <div class="page-bar">
                        <div class="page-title-breadcrumb">
                            <div class=" pull-left">
                                <div class="page-title">Profile Manager</div>
                            </div>
                            <ol class="breadcrumb page-breadcrumb pull-right">
                                @include('admin.includes.breadcrumb_dashboard_link')
                                <li><a class="parent-item" href="{{ route('admin.profile')}}">Profile</a>&nbsp;<i class="fa fa-angle-right"></i>
                                </li>
                                <li class="active">Update</li>
                            </ol>
                        </div>
                    </div>
                     <div class="row">
							<div class="col-sm-12">
							@include('admin.includes.flash_messages')

								<div class="card-box">
									<div class="card-head">
										<header>Basic Information</header>
										<button id = "panel-button" 
				                           class = "mdl-button mdl-js-button mdl-button--icon pull-right" 
				                           data-upgraded = ",MaterialButton">
				                           <i class = "material-icons">more_vert</i>
				                        </button>
				                        <ul class = "mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
				                           data-mdl-for = "panel-button">
				                           <li class = "mdl-menu__item"><i class="material-icons">assistant_photo</i>Action</li>
				                           <li class = "mdl-menu__item"><i class="material-icons">print</i>Another action</li>
				                           <li class = "mdl-menu__item"><i class="material-icons">favorite</i>Something else here</li>
				                        </ul>
									</div>
									<div class="card-body row">
							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "name"
						                     value="{{ $data['user']->name }}" type = "text">
						                     <label for = "name" class = "mdl-textfield__label {{ $errors->has('name') ? ' is-invalid' : '' }}">User Name</label>

						                     @if ($errors->has('name'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('name') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div>

							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "email" value="{{ $data['user']->email }}" type = "">
						                     <label for = "email" class = "mdl-textfield__label {{ $errors->has('email') ? ' is-invalid' : '' }}">Email</label>

						                     @if ($errors->has('email'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('email') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 

							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "first_name" value="{{ $data['user']->first_name }}" type = "text">
						                     <label for = "first_name" class = "mdl-textfield__label {{ $errors->has('first_name') ? ' is-invalid' : '' }}">First Name</label>

						                     @if ($errors->has('first_name'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('first_name') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 

							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "middle_name" value="{{ $data['user']->middle_name }}" type = "text">
						                     <label for = "middle_name" class = "mdl-textfield__label {{ $errors->has('middle_name') ? ' is-invalid' : '' }}">Middle Name</label>

						                     @if ($errors->has('middle_name'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('middle_name') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 



							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "last_name" value="{{ $data['user']->last_name }}" type = "text">
						                     <label for = "last_name" class = "mdl-textfield__label {{ $errors->has('last_name') ? ' is-invalid' : '' }} ">Last Name</label>

						                     @if ($errors->has('last_name'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('last_name') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 


							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "contact" value="{{ $data['user']->contact }}" type = "text">
						                     <label for = "contact" class = "mdl-textfield__label {{ $errors->has('contact') ? ' is-invalid' : '' }}">Contact</label>

						                     @if ($errors->has('contact'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('contact') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 


							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <textarea name="address" id="" cols="30" rows="10" class="form-control">{{ $data['user']->address }}</textarea>
						                     <label for = "address" class = "mdl-textfield__label {{ $errors->has('address') ? ' is-invalid' : '' }}">Address</label>

						                     @if ($errors->has('contact'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('address') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 


							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "password" type = "">
						                     <label for = "password" class = "mdl-textfield__label {{ $errors->has('password') ? ' is-invalid' : '' }}">Password</label>

						                     @if ($errors->has('password'))
			                                    <span class="invalid-feedback" role="alert">
			                                        <strong>{{ $errors->first('password') }}</strong>
			                                    </span>
                                			@endif

						                  </div>
							            </div> 

							            <div class="col-lg-6 p-t-20"> 
							              <div class = "mdl-textfield mdl-js-textfield mdl-textfield--floating-label txt-full-width">
						                     <input class = "mdl-textfield__input" name = "password_confirmation" type = "">
						                     <label for = "password_confirmation" class = "mdl-textfield__label">Confirm New Password</label>
						                  </div>
							            </div>
							        
								         <div class="col-lg-12 p-t-20 text-center"> 
							              	<button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 m-r-20 btn-pink">Update</button>
											<button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect m-b-10 btn-default">Cancel</button>
							            </div>
									</div>
								</div>
							</div>
						</div> 
                </div>
            </div>

{{ Form::close() }}
@endsection