routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin/', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function(){
 			
 			Route::get('dashboard',  ['as' => 'dashboard',  'uses' => 'DashboardController@index']);
 			Route::get('profile',  ['as' => 'profile',  'uses' => 'UserController@profile']);
 			Route::post('profile',  ['as' => 'profile.update',  'uses' => 'UserController@profileUpdate']);
 			//Route::resource('user', 'UserController');
 			Route::resource('roomtypes', 'RoomTypeController');
 			Route::resource('hotel', 'HotelController');
 			Route::resource('reservation', 'ReservationController');
 			Route::resource('inquiry', 'InquiryController');
 			Route::get('reservation/publish/{id}', 'ReservationController@publish')->name('reservation.publish');
 			Route::get('reservation/genderone/{id}', 'ReservationController@genderone')->name('reservation.genderone');

 			Route::resource('addstaff', 'AddStaffController');
 			Route::resource('room', 'RoomController');


			Route::resource('service', 'ServicesController');
 			Route::resource('slider', 'SliderController');
 			Route::get('slider/publish/{id}', 'SliderController@publish')->name('slider.publish');
 			
 			Route::resource('amenity', 'AmenityController');

 			Route::get('roomtypes/{id}/delete', ['as' => 'roomtypes.delete', 'uses' => 'RoomTypeController@destroy']);


 			Route::get('room/{id}/delete', ['as' => 'room.delete', 'uses' => 'RoomController@destroy']);




});

Auth::routes();

/*FrontEnd*/
Route::get('/', 'Web\HomeController@index')->name('home');
Route::get('/about-us', 'Web\HomeController@aboutUs')->name('about-us');
Route::get('/services', 'Web\HomeController@services')->name('services');
Route::get('/rooms', 'Web\RoomsController@index')->name('rooms');
Route::get('reservation/{id}', 'Web\RoomsController@booking')->name('reservation.booking');
Route::get('reservation/publish/', 'Web\RoomsController@publish')->name('reservation.publish');
Route::get('/rooms/{id}', 'Web\RoomsController@getSingleRoom')->name('rooms.title');
Route::get('/contact', 'Web\HomeController@contact')->name('contact');
Route::post('/submitContactForm', 'Web\HomeController@submitContactForm')->name('submitContactForm');

resources/views/admin/includes/breadcrumb_dashboard_link.blade.php
<li>
	<i class="fa fa-home">
	</i>&nbsp;<a class="parent-item" href="{{ $dashboard_url }}">Home</a>&nbsp;
	<i class="fa fa-angle-right"></i>
</li>

resources/views/admin/includes/flash_messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if(session()->has('success_message'))
        <div class="alert alert-success">
              <strong>Well done!</strong>
               {{ session()->get('success_message') }}
        </div>
       
    
@endif

resources/views/admin/includes/footer.blade.php
<div class="page-footer">
    <div class="page-footer-inner"> 2018 &copy; KTM Hotel Template By
        <a href="mailto:something@gmail.com" target="_top" class="makerCss">Laravel Theme</a>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

resources/views/admin/includes/header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <div class="page-header-inner ">
        <!-- logo start -->
        <div class="page-logo">
            <a href="index.html">
                <img alt="" src="{{ asset('assets/admin/img/logo.png') }}">
                <span class="logo-default" >Ktm</span> </a>
        </div>
        <!-- logo end -->
        <ul class="nav navbar-nav navbar-left in">
            <li><a href="#" class="menu-toggler sidebar-toggler"><i class="icon-menu"></i></a></li>
        </ul>
        <form class="search-form-opened" action="#" method="GET">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search..." name="query">
                <span class="input-group-btn search-btn">
                          <a href="javascript:;" class="btn submit">
                             <i class="icon-magnifier"></i>
                           </a>
                        </span>
            </div>
        </form>

        <!-- start mobile menu -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- end mobile menu -->
        <!-- start header menu -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                <!-- start notification dropdown -->
                <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="fa fa-bell-o"></i>
                        <span class="badge headerBadgeColor1"> 6 </span>
                    </a>
                    <ul class="dropdown-menu animated swing">
                        <li class="external">
                            <h3><span class="bold">Notifications</span></h3>
                            <span class="notification-label purple-bgcolor">New 6</span>
                        </li>
                        <li>
                            <ul class="dropdown-menu-list small-slimscroll-style" data-handle-color="#637283">
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">just now</span>
                                        <span class="details">
                                                <span class="notification-icon circle deepPink-bgcolor"><i class="fa fa-check"></i></span> Congratulations!. </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">3 mins</span>
                                        <span class="details">
                                                <span class="notification-icon circle purple-bgcolor"><i class="fa fa-user o"></i></span>
                                                <b>John Micle </b>is now following you. </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">7 mins</span>
                                        <span class="details">
                                                <span class="notification-icon circle blue-bgcolor"><i class="fa fa-comments-o"></i></span>
                                                <b>Sneha Jogi </b>sent you a message. </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">12 mins</span>
                                        <span class="details">
                                                <span class="notification-icon circle pink"><i class="fa fa-heart"></i></span>
                                                <b>Ravi Patel </b>like your photo. </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">15 mins</span>
                                        <span class="details">
                                                <span class="notification-icon circle yellow"><i class="fa fa-warning"></i></span> Warning! </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <span class="time">10 hrs</span>
                                        <span class="details">
                                                <span class="notification-icon circle red"><i class="fa fa-times"></i></span> Application error. </span>
                                    </a>
                                </li>
                            </ul>
                            <div class="dropdown-menu-footer">
                                <a href="javascript:void(0)"> All notifications </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- end notification dropdown -->
                <!-- start message dropdown -->
                <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge headerBadgeColor2"> 2 </span>
                    </a>
                    <ul class="dropdown-menu animated slideInDown">
                        <li class="external">
                            <h3><span class="bold">Messages</span></h3>
                            <span class="notification-label cyan-bgcolor">New 2</span>
                        </li>
                        <li>
                            <ul class="dropdown-menu-list small-slimscroll-style" data-handle-color="#637283">
                                <li>
                                    <a href="#">
                                                <span class="photo">
                                                	<img src="{{ asset('assets/admin/img/user/user2.jpg') }}" class="img-circle" alt=""> </span>
                                        <span class="subject">
                                                	<span class="from"> Sarah Smith </span>
                                                	<span class="time">Just Now </span>
                                                </span>
                                        <span class="message"> Jatin I found you on LinkedIn... </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                                <span class="photo">
                                                	<img src="{{ asset('assets/admin/img/user/user3.jpg') }}" class="img-circle" alt=""> </span>
                                        <span class="subject">
                                                	<span class="from"> John Deo </span>
                                                	<span class="time">16 mins </span>
                                                </span>
                                        <span class="message"> Fwd: Important Notice Regarding Your Domain Name... </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                                <span class="photo">
                                                	<img src="assets/img/user/user1.jpg" class="img-circle" alt=""> </span>
                                        <span class="subject">
                                                	<span class="from"> Rajesh </span>
                                                	<span class="time">2 hrs </span>
                                                </span>
                                        <span class="message"> pls take a print of attachments. </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                                <span class="photo">
                                                	<img src="assets/img/user/user8.jpg" class="img-circle" alt=""> </span>
                                        <span class="subject">
                                                	<span class="from"> Lina Smith </span>
                                                	<span class="time">40 mins </span>
                                                </span>
                                        <span class="message"> Apply for Ortho Surgeon </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                                <span class="photo">
                                                	<img src="assets/img/user/user5.jpg" class="img-circle" alt=""> </span>
                                        <span class="subject">
                                                	<span class="from"> Jacob Ryan </span>
                                                	<span class="time">46 mins </span>
                                                </span>
                                        <span class="message"> Request for leave application. </span>
                                    </a>
                                </li>
                            </ul>
                            <div class="dropdown-menu-footer">
                                <a href="#"> All Messages </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- end message dropdown -->
                <!-- start manage user dropdown -->

                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle " src="{{ asset('assets/admin/img/user/sk.jpg') }}" />
                        <span class="username username-hide-on-mobile"> {{ auth()->user()->name }} </span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default animated jello">
                        <li>
                            <a href="{{ route('admin.profile') }}">


                                <i class="icon-user"></i> Profile </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-settings"></i> Settings
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-directions"></i> Help
                            </a>
                        </li>
                        <li class="divider"> </li>
                        <li>
                            <a href="lock_screen.html">
                                <i class="icon-lock"></i> Lock
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                <i class="icon-logout"></i> 
                                Log Out 
                            </a>
                            <form method="POST" action="{{ route('logout') }}" id="logout-form" style="display: none;">
                                {!! csrf_field() !!}
                            </form>
                        </li>
                    </ul>
                </li>
                <!-- end manage user dropdown -->
                <li class="dropdown dropdown-quick-sidebar-toggler">
                    <a id="headerSettingButton" class="mdl-button mdl-js-button mdl-button--icon pull-right" data-upgraded=",MaterialButton">
                        <i class="material-icons">settings</i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    
</div>

resources/views/admin/includes/sidebar.blade.php
<div class="sidebar-container">
    <div class="sidemenu-container navbar-collapse collapse fixed-menu">
        <div id="remove-scroll">
            <ul class="sidemenu page-header-fixed p-t-20" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <!-- start User Profile menu -->
            <li class="sidebar-user-panel">
                <div class="user-panel">
                    <div class="row">
                        <div class="sidebar-userpic">
                            <img src="{{ asset('assets/admin/img/dp.jpg') }}" class="img-responsive" alt="">
                        </div>
                    </div>
                    <div class="profile-usertitle">
                        <div class="sidebar-userpic-name"> {{Auth::user()->title}} </div>
                        <div class="profile-usertitle-job"> Manager </div>
                    </div>
                    <div class="sidebar-userpic-btn">
                            <a class="tooltips" href="{{ route('admin.profile') }}" data-placement="top" data-original-title="Profile">
                                <i class="material-icons">person_outline</i>
                            </a>
                            <a class="tooltips" href="email_inbox.html" data-placement="top" data-original-title="Mail">
                                <i class="material-icons">mail_outline</i>
                            </a>
                            <a class="tooltips" href="chat.html" data-placement="top" data-original-title="Chat">
                                <i class="material-icons">chat</i>
                            </a>
                            <a class="tooltips" href="login.html" data-placement="top" data-original-title="Logout">
                                <i class="material-icons">input</i>
                            </a>
                    </div>
                </div>
            </li>
            <!-- End User Profile menu -->
                <li class="menu-heading">
                    <span>Main Menu</span>
                </li>
                <li class="nav-item start">
                    <a href="{{ route('admin.dashboard') }}"> <i class="material-icons">dashboard</i>  Dashboard
                        {{-- <span class="arrow "></span> --}}
                    </a>
                </li>

               {{--  <li class="nav-item {!! request()->is('admin/user*')? 'active open':'' !!}" >
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">assignment_turned_in</i>
                        <span class="title">Users</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/user')? 'active':'' !!}" >
                            <a href="{{ route('admin.user.index') }}" class="nav-link ">
                                <span class="title">All Users</span>
                            </a>
                        </li>

                        <li class="nav-item {!! request()->is('admin/user/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.user.create') }}" class="nav-link ">
                                <span class="title">Add Users</span>
                            </a>
                        </li>
                    </ul>
                </li>
 --}}
                <li class="nav-item {!! request()->is('admin/reservation*')?' active open':'' !!}">
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">business_center</i>
                        <span class="title">Reservation</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/reservation')? 'class="active"':'' !!}" >
                            <a href="{{ route('admin.reservation.index') }}" class="nav-link ">
                                <span class="title">Reservation List</span>
                            </a>
                        </li>
                        <li class="nav-item{!! request()->is('admin/reservation/create')? 'class="active"':'' !!}" >
                            <a href="{{ route('admin.reservation.create') }}" class="nav-link ">
                                <span class="title">Add Reservation</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item {!! request()->is('admin/room*')? 'active open':'' !!}" >
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">vpn_key</i>
                        <span class="title">Rooms</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/room')? 'active':'' !!}" >
                            <a href="{{ route('admin.room.index') }}" class="nav-link ">
                                <span class="title">View All Rooms</span>
                            </a>
                        </li>

                        <li class="nav-item {!! request()->is('admin/room/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.room.create') }}" class="nav-link ">
                                <span class="title">Add New Room</span>
                            </a>
                        </li>
                    </ul>
                </li>
            
                <li class="nav-item {!! request()->is('admin/roomtypes*')? 'active open':'' !!}" >
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">assignment_turned_in</i>
                        <span class="title">Rooms Type</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/roomtypes')? 'active':'' !!}" >
                            <a href="{{ route('admin.roomtypes.index') }}" class="nav-link ">
                                <span class="title">   All Room Type</span>
                            </a>
                        </li>

                        <li class="nav-item {!! request()->is('admin/roomtypes/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.roomtypes.create') }}" class="nav-link ">
                                <span class="title">Add Room Type</span>
                            </a>
                        </li>
                    </ul>
                </li>

 
                <li class="nav-item {!! request()->is('admin/amenity*')? 'active open':'' !!}" >
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">assignment_turned_in</i>
                        <span class="title">Amenity</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/amenity')? 'active':'' !!}" >
                            <a href="{{ route('admin.amenity.index') }}" class="nav-link ">
                                <span class="title">   All amenity</span>
                            </a>
                        </li>

                        <li class="nav-item {!! request()->is('admin/amenity/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.amenity.create') }}" class="nav-link ">
                                <span class="title">Add amenity</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item {!! request()->is('admin/slider*')? 'active open':'' !!}" >
 
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">collections</i>
                        <span class="title">Slider</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/slider')? 'active':'' !!}" >
                            <a href="{{ route('admin.slider.index') }}" class="nav-link ">
                                <span class="title">All Sliders</span>
                            </a>
                        </li>
                        <li class="nav-item {!! request()->is('admin/slider/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.slider.create') }}" class="nav-link ">
                                <span class="title">Add Slider</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">grade</i>
                        <span class="title">Services</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/service*')? 'active open':'' !!}" >
                            <a href="{{ route('admin.service.index') }}" class="nav-link ">
                                <span class="title">All Services</span>
                            </a>
                        </li>

                        <li class="nav-item {!! request()->is('admin/service/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.service.create') }}" class="nav-link ">
                                <span class="title">Add Service</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item {!! request()->is('admin/addstaff*')? 'active open':'' !!}" >
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">people</i>
                        <span class="title">Staff</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/addstaff/create')? 'active':'' !!}" >
                            <a href="{{ route('admin.addstaff.create') }}" class="nav-link ">
                                <span class="title">Add Staff Details</span>
                            </a>
                        </li>
                        <li class="nav-item {!! request()->is('admin/addstaff')? 'active':'' !!}" >
                            <a href="{{ route('admin.addstaff.index') }}" class="nav-link ">
                                <span class="title">View All Staffs</span>
                            </a>
                        </li>
                        
                    </ul>
                </li>

                 <li class="nav-item {!! request()->is('admin/inquiry*')?'class="active open"':'' !!}">
                    <a href="#" class="nav-link nav-toggle">
                        <i class="material-icons">business_center</i>
                        <span class="title">Inquiry</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        <li class="nav-item {!! request()->is('admin/inquiry*')? 'active':'' !!}" >
                            <a href="{{ route('admin.inquiry.index') }}" class="nav-link ">
                                <span class="title">Inquiry List</span>
                            </a>
                        </li>
                        {{-- <li class="nav-item">
                            <a href="{{ route('admin.inquiry.create') }}" class="nav-link ">
                                <span class="title">Add Inquiry</span>
                            </a>
                        </li> --}}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>